<a href="https://colab.research.google.com/github/Vga18/diplomado/blob/main/Proyecto_diplomado.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Cont-AI**

## **Planteamiento del problema**

El desarrollo de pólizas es un proceso automático y tardado, ya que requiere tener un criterio para decidir que gastos van su cuenta contable

Plataforma de usuario para agilizar la capturación de pólizas de egresos

Acotado a las facturas XML-CFDI recibidas, y al catalogo de cuentas contables que maneja el Sistema Aspel COI versión 9

## Librerias

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px


pd.set_option("display.max_columns",200)
pd.set_option("display.max_rows",100)

## Funciones Auxiliares

## Datos

In [2]:
catalogo = pd.read_csv(r"/content/Datos/catalogo de cuentas contables.csv")

## Ingenieria

In [3]:
catalogo.sample(5)

,NUM_CTA,STATUS,TIPO,NOMBRE,DEPTSINO,BANDMULTI,BANDAJT,CTA_PAPA,CTA_RAIZ,NIVEL,CTA_COMP,NATURALEZA,RFC,CODAGRUP,CAPTURACHEQUE,CAPTURAUUID,BANCO,CTABANCARIA,CAPCHEQTIPOMOV,NOINCLUIRXML,IDFISCAL,ESFLUJODEEFECTIVO,BANCOEXTRANJERO,RFCFLUJO
202,620002200000000000002,A,D,MANTTO. EQUIPO DE TRANSPORTE,N,1,N,620000000000000000001,620000000000000000001,2,NaN,0,NaN,603.56,0,0,0,NaN,N,0,NaN,NaN,NaN,NaN
182,620000200000000000002,A,D,ASIMILADOS A SALARIOS,N,1,N,620000000000000000001,620000000000000000001,2,NaN,0,NaN,603.31,0,0,0,NaN,N,0,NaN,NaN,NaN,NaN
160,610003700000000000002,A,D,OTROS IMPUESTOS Y DERECHOS,N,1,N,610000000000000000001,610000000000000000001,2,NaN,0,NaN,602.58,0,0,0,NaN,N,0,NaN,NaN,NaN,NaN
17,118000000000000000001,A,A,IMPUESTOS A FAVOR,N,1,N,-1,118000000000000000001,1,NaN,0,NaN,113.00,0,0,0,NaN,NaN,0,NaN,NaN,NaN,NaN
281,920000300000000000002,A,D,CONTRA CTA. CUFIN DE EJER. ANTERIORES,N,1,N,920000000000000000001,920000000000000000001,2,NaN,1,NaN,803.02,0,0,0,NaN,N,0,NaN,NaN,NaN,NaN

Ya que el objetivo es la clasificación de numero de cuentas se eligira ciertas variables

In [4]:
catalogo = catalogo[["NUM_CTA","STATUS","TIPO","NOMBRE","NIVEL","NATURALEZA"]]
catalogo = catalogo[catalogo['NIVEL'] != 3]
catalogo.sample(5)

,NUM_CTA,STATUS,TIPO,NOMBRE,NIVEL,NATURALEZA
59,147000000000000000001,A,A,DEPOSITOS EN GARANTIA,1,0
101,310000000000000000001,A,A,CAPITAL SOCIAL,1,1
121,500000000000000000001,A,A,COSTO DE VENTAS,1,0
154,610003100000000000002,A,D,HONORARIOS PERSONAS FISICAS,2,0
278,920000000000000000001,A,A,CUENTAS DE ORDEN FISCALES ACREEDORAS,1,1